export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const LIKE = 'LIKE';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST';
export const FETCH_FRIEND_REQUESTS = 'FETCH_FRIEND_REQUESTS';
export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';
export const DECLINE_FRIEND_REQUEST = 'DECLINE_FRIEND_REQUEST';

export const FETCH_FOLLOWING = 'FETCH_FOLLOWING';
export const FETCH_FOLLOWERS = 'FETCH_FOLLOWERS';
export const REMOVE_USER_FROM_FOLLOWING = 'REMOVE_USER_FROM_FOLLOWING';

export const GET_USER_POSTS = 'GET_USER_POSTS';
export const DELETE_USER_POST = 'UPDATE_USER_POSTS';

export const GET_REWARDS = 'GET_REWARDS';

export const RESET = 'RESET';
